#!/usr/bin/env bash
# Opens or updates a `ci-health` issue when a scheduled workflow fails.
#
# Scheduled workflows fail quietly. The flakiness report failed 22 days
# straight, then stopped firing for ~10 weeks, and nobody learned of any of
# the three transitions (#431). GitHub emails the workflow file's last
# committer on a scheduled-run failure — the 22 failures presumably produced
# 22 such emails and no action, which is evidence about that channel rather
# than about the people.
#
# So the report's own escalation mechanism gets pointed at the report's own
# health: one rolling issue per workflow, updated in place, closed on the
# next success. A monitoring job that can fail without saying so is worth
# less than its green runs suggest.
#
# Usage: report_scheduled_failure.sh <workflow-name> <run-url>
# Requires: GH_TOKEN with issues:write.

set -euo pipefail

WORKFLOW="${1:?usage: report_scheduled_failure.sh <workflow-name> <run-url>}"
RUN_URL="${2:?usage: report_scheduled_failure.sh <workflow-name> <run-url>}"

TITLE="Scheduled workflow failing: $WORKFLOW"

gh label create "ci-health" \
  --description "CI health and flakiness tracking" \
  --color "fbca04" \
  2>/dev/null || true

# `--state all` for the same reason the API sweep uses it: an issue closed
# without the underlying failure being fixed would otherwise get a fresh
# duplicate filed every morning.
EXISTING=$(gh issue list \
  --label "ci-health" \
  --state all \
  --limit 100 \
  --json number,title \
  --jq '[.[] | select(.title == $ENV.TITLE) | .number] | first // empty')

export TITLE

{
  echo "\`$WORKFLOW\` failed on its scheduled run."
  echo
  echo "- Most recent failing run: $RUN_URL"
  echo "- This issue is opened by the workflow itself and **closes**"
  echo "  automatically on the next successful run."
  echo
  echo "Scheduled workflows fail quietly — the only other signal is an email"
  echo "to whoever last committed the workflow file, which does not survive a"
  echo "change of maintainer. See #431 for the history that motivated this."
  echo
  echo "---"
  echo "_Generated by [Claude Code](https://claude.ai/code)_"
} > failure_report.md

if [ -n "$EXISTING" ]; then
  gh issue reopen "$EXISTING" 2>/dev/null || true
  gh issue edit "$EXISTING" --body-file failure_report.md
  # A body edit notifies nobody, so a run that fails again after a reopen
  # would otherwise be silent.
  gh issue comment "$EXISTING" --body "Still failing: $RUN_URL

---
_Generated by [Claude Code](https://claude.ai/code)_"
  echo "Updated issue #$EXISTING"
else
  gh issue create \
    --title "$TITLE" \
    --body-file failure_report.md \
    --label "ci-health"
fi
