#!/usr/bin/env bash
# Opens or updates a `ci-health` issue when a scheduled workflow fails.
#
# Scheduled workflows fail quietly. The flakiness report failed 22 days
# straight, then stopped firing for ~10 weeks, and nobody learned of any of
# the three transitions (#431). GitHub emails the workflow file's last
# committer on a scheduled-run failure — the 22 failures presumably produced
# 22 such emails and no action, which is evidence about that channel rather
# than about the people.
#
# So the report's own escalation mechanism gets pointed at the report's own
# health: one rolling issue per workflow, updated in place, closed by
# `resolve_scheduled_failure.sh` on the next success. A monitoring job that
# can fail without saying so is worth less than its green runs suggest.
#
#
# Boundary worth naming: this runs inside the job it reports on and reads its
# own script from the checkout, so a scheduled run that dies *before or
# during* `actions/checkout` fails as silently as it did before #431. That is
# the one sub-case an in-job mechanism cannot cover; the general
# not-running-at-all case is the deferred liveness work.
# Usage: report_scheduled_failure.sh <workflow-name> <run-url>
# Requires: GH_TOKEN with issues:write.

set -euo pipefail

WORKFLOW="${1:?usage: report_scheduled_failure.sh <workflow-name> <run-url>}"
RUN_URL="${2:?usage: report_scheduled_failure.sh <workflow-name> <run-url>}"

# Exported before the query below, not after: the `--jq` filter reads
# `$ENV.TITLE`, which resolves in the environment of the `gh` child process.
# As a plain shell variable it would be absent there, `$ENV.TITLE` would be
# null, `select(.title == null)` would match nothing, and every failing run
# would file a fresh duplicate while the update path below never ran.
export TITLE="Scheduled workflow failing: $WORKFLOW"

# Looked up by a dedicated label, not by `ci-health`.
#
# `ci-health` is shared with the flakiness report, which currently files a
# *new* issue every day (#425 fixes that, but this must not depend on it).
# `gh issue list` is newest-first and capped, and this rolling issue is
# created once and thereafter only edited — edits do not bump created_at, so
# it sinks steadily. At roughly 100 newer issues it falls off the page, the
# lookup returns empty, and every failure files a duplicate: exactly the
# flood this script exists to avoid.
#
# A label only these two scripts apply keeps the population at one per
# watched workflow. `ci-health` is applied as well, so the issues still show
# up in the existing view.
ESCALATION_LABEL="ci-health-escalation"

gh label create "$ESCALATION_LABEL" \
  --description "A scheduled workflow is failing (opened by the workflow itself)" \
  --color "b60205" \
  2>/dev/null || true
gh label create "ci-health" \
  --description "CI health and flakiness tracking" \
  --color "fbca04" \
  2>/dev/null || true

# `--state all` for the same reason the API sweep uses it: an issue closed
# without the underlying failure being fixed would otherwise get a fresh
# duplicate filed every morning.
EXISTING=$(gh issue list \
  --label "$ESCALATION_LABEL" \
  --state all \
  --limit 100 \
  --json number,title \
  --jq '[.[] | select(.title == $ENV.TITLE) | .number] | first // empty')

# mktemp rather than the working directory: this runs inside a checkout, and
# a stray report file in the repo root is the kind of thing a later step
# picks up by accident.
BODY=$(mktemp)
trap 'rm -f "$BODY"' EXIT

{
  echo "\`$WORKFLOW\` failed on its scheduled run."
  echo
  echo "- Most recent failing run: $RUN_URL"
  echo "- This issue is opened by the workflow itself and **closes**"
  echo "  automatically on the next successful run."
  echo
  echo "Scheduled workflows fail quietly — the only other signal is an email"
  echo "to whoever last committed the workflow file, which does not survive a"
  echo "change of maintainer. See #431 for the history that motivated this."
  echo
  echo "---"
  echo "_Generated by [Claude Code](https://claude.ai/code)_"
} > "$BODY"

if [ -n "$EXISTING" ]; then
  gh issue reopen "$EXISTING" 2>/dev/null || true
  gh issue edit "$EXISTING" --body-file "$BODY"
  # A body edit notifies nobody and does not bump the issue in an inbox, so
  # a second consecutive failure would otherwise be silent.
  gh issue comment "$EXISTING" --body "Still failing: $RUN_URL

---
_Generated by [Claude Code](https://claude.ai/code)_"
  echo "Updated issue #$EXISTING"
else
  gh issue create \
    --title "$TITLE" \
    --body-file "$BODY" \
    --label "$ESCALATION_LABEL" \
    --label "ci-health"
fi
