#!/usr/bin/env bash
# Opens or updates a `ci-health` issue when a scheduled workflow fails: one
# rolling issue per workflow, closed by `resolve_scheduled_failure.sh` on the
# next success (#431).
#
# Runs from the checkout, so a run that dies before checkout still fails
# silently.
# Usage: report_scheduled_failure.sh <workflow-name> <run-url> [context]
# Requires: GH_TOKEN with issues:write.

set -euo pipefail

WORKFLOW="${1:?usage: report_scheduled_failure.sh <workflow-name> <run-url> [context]}"
RUN_URL="${2:?usage: report_scheduled_failure.sh <workflow-name> <run-url> [context]}"

# Optional third argument: the body's explanatory paragraph, for workflows such
# as Security Audit where the default monitoring framing reads wrong.
CONTEXT="${3:-Scheduled workflows fail quietly — the only other signal is an email
to whoever last committed the workflow file, which does not survive a
change of maintainer. See #431 for the history that motivated this.}"

# Exported: `$ENV.TITLE` in the `--jq` filter reads the `gh` process
# environment.
export TITLE="Scheduled workflow failing: $WORKFLOW"

# A dedicated label, not the shared `ci-health`: this rarely-bumped issue would
# sink past `--limit` there and then be duplicated.
ESCALATION_LABEL="ci-health-escalation"

gh label create "$ESCALATION_LABEL" \
  --description "A scheduled workflow is failing (opened by the workflow itself)" \
  --color "b60205" \
  2>/dev/null || true
gh label create "ci-health" \
  --description "CI health and flakiness tracking" \
  --color "fbca04" \
  2>/dev/null || true

# `--state all`: an issue closed without a fix is reopened, not duplicated.
EXISTING=$(gh issue list \
  --label "$ESCALATION_LABEL" \
  --state all \
  --limit 100 \
  --json number,title \
  --jq '[.[] | select(.title == $ENV.TITLE) | .number] | first // empty')

# Streak, derived from the issue's own comments: failure comments since the last
# recovery, plus this run, plus the opening run if there was no recovery.
# RECOVERY_PREFIX is shared with `resolve_scheduled_failure.sh`; the harness
# checks they agree.
FAILURE_PREFIX="Still failing"
RECOVERY_PREFIX="Recovered"

streak_line() {
  local issue="$1" view parsed
  view=$(gh issue view "$issue" --json createdAt,comments 2>/dev/null) || return 0
  parsed=$(jq -r \
    --arg recovered "$RECOVERY_PREFIX" \
    --arg failing "$FAILURE_PREFIX" '
    ((.comments // []) | length) as $total
    | ((.comments // []) | map(.body | startswith($recovered)) | rindex(true)) as $r
    | (if $r == null
       then {opened: .createdAt, rest: (.comments // [])}
       else {opened: null,       rest: ((.comments // [])[($r + 1):])}
       end)
    | (.rest | map(select(.body | startswith($failing)))) as $sf
    | "\(($sf | length) + (if .opened == null then 1 else 2 end))|\(.opened // $sf[0].createdAt // "")|\($total >= 100)"
  ' <<<"$view" 2>/dev/null) || return 0

  # `|`, not a tab: IFS collapses runs of whitespace delimiters and would drop
  # an empty middle field.
  local count since capped
  IFS='|' read -r count since capped <<<"$parsed"
  [ -n "$count" ] || return 0
  # No timestamp means this run is itself the start of the streak.
  since=${since:0:10}
  [ -n "$since" ] || since=$(date -u +%Y-%m-%d)

  local runs="consecutive scheduled runs"
  [ "$count" = "1" ] && runs="scheduled run"

  # `--json comments` returns only the oldest 100, so past that no count is
  # trustworthy, not even as a floor.
  if [ "$capped" = "true" ]; then
    echo "- **Still failing.** (The comment history is truncated at one API"
    echo "  page, so the streak length cannot be determined from it — it may"
    echo "  have restarted since the oldest comment shown.)"
    return 0
  fi
  echo "- **Failing since $since — $count $runs.**"
}

# mktemp, so no stray file lands in the checkout.
BODY=$(mktemp)
trap 'rm -f "$BODY"' EXIT

# `--body-file` overwrites, so anything a maintainer adds below this marker is
# carried forward.
EDIT_MARKER="<!-- Generated above; anything you add below this line is preserved. -->"
PRESERVED=""
if [ -n "$EXISTING" ]; then
  PRESERVED=$(gh issue view "$EXISTING" --json body --jq .body 2>/dev/null \
    | awk -v marker="$EDIT_MARKER" '
        { line = $0; sub(/\r$/, "", line) }
        found { print }
        line == marker { found = 1 }') || PRESERVED=""
fi

{
  echo "\`$WORKFLOW\` failed on its scheduled run."
  echo
  echo "- Most recent failing run: $RUN_URL"
  [ -n "$EXISTING" ] && streak_line "$EXISTING"
  # Names no trigger: the two callers gate their resolve steps differently.
  echo "- This issue is opened by the workflow itself and **closes**"
  echo "  automatically once this workflow next succeeds on the trigger that"
  echo "  opened it."
  echo
  echo "$CONTEXT"
  echo
  echo "---"
  echo "_Generated by [Claude Code](https://claude.ai/code)_"
  echo
  echo "$EDIT_MARKER"
  # `if`, not `[ ] && printf`: as the group's last command a false test would
  # make the whole group exit 1.
  if [ -n "$PRESERVED" ]; then
    printf '%s\n' "$PRESERVED"
  fi
} > "$BODY"

if [ -n "$EXISTING" ]; then
  gh issue reopen "$EXISTING" 2>/dev/null || true
  gh issue edit "$EXISTING" --body-file "$BODY"
  # A body edit notifies nobody and does not bump the issue in an inbox, so
  # a second consecutive failure would otherwise be silent.
  gh issue comment "$EXISTING" --body "$FAILURE_PREFIX: $RUN_URL

---
_Generated by [Claude Code](https://claude.ai/code)_"
  echo "Updated issue #$EXISTING"
else
  gh issue create \
    --title "$TITLE" \
    --body-file "$BODY" \
    --label "$ESCALATION_LABEL" \
    --label "ci-health"
fi
