#!/usr/bin/env bash
# Closes the `ci-health` issue for a scheduled workflow that has recovered.
#
# The counterpart to `report_scheduled_failure.sh`. Without it the issue
# stays open after the failure is fixed, and a signal that is always on is
# no signal — the same argument as the API sweep's close step.
#
#
# Boundary worth naming: this runs inside the job it reports on and reads its
# own script from the checkout, so a scheduled run that dies *before or
# during* `actions/checkout` fails as silently as it did before #431. That is
# the one sub-case an in-job mechanism cannot cover; the general
# not-running-at-all case is the deferred liveness work.
# Usage: resolve_scheduled_failure.sh <workflow-name>
# Requires: GH_TOKEN with issues:write.

set -euo pipefail

WORKFLOW="${1:?usage: resolve_scheduled_failure.sh <workflow-name>}"

# Exported before the query, so the `--jq` filter's `$ENV.TITLE` resolves in
# the `gh` child process. See the longer note in the reporting script.
export TITLE="Scheduled workflow failing: $WORKFLOW"

# The same dedicated label the reporting script files under — see the long
# note there. If these two lookups drift apart, updates land on one issue
# while closes target another.
ESCALATION_LABEL="ci-health-escalation"

# Open only: a closed one is already resolved.
EXISTING=$(gh issue list \
  --label "$ESCALATION_LABEL" \
  --state open \
  --limit 100 \
  --json number,title \
  --jq '[.[] | select(.title == $ENV.TITLE) | .number] | first // empty')

if [ -z "$EXISTING" ]; then
  echo "No open failure issue for '$WORKFLOW'."
  exit 0
fi

gh issue comment "$EXISTING" --body "Recovered — the scheduled run succeeded. Closing.

---
_Generated by [Claude Code](https://claude.ai/code)_"
gh issue close "$EXISTING" --reason completed
echo "Closed issue #$EXISTING"
