#!/usr/bin/env bash
# Closes the `ci-health` issue for a scheduled workflow that has recovered.
#
# The counterpart to `report_scheduled_failure.sh`: an issue left open after a
# fix is no signal.
#
# Usage: resolve_scheduled_failure.sh <workflow-name>
# Requires: GH_TOKEN with issues:write.

set -euo pipefail

WORKFLOW="${1:?usage: resolve_scheduled_failure.sh <workflow-name>}"

# Exported so the `--jq` filter's `$ENV.TITLE` sees it.
export TITLE="Scheduled workflow failing: $WORKFLOW"

# Must match the reporter's label, or updates and closes target different
# issues.
ESCALATION_LABEL="ci-health-escalation"

# Open only: a closed one is already resolved.
EXISTING=$(gh issue list \
  --label "$ESCALATION_LABEL" \
  --state open \
  --limit 100 \
  --json number,title \
  --jq '[.[] | select(.title == $ENV.TITLE) | .number] | first // empty')

if [ -z "$EXISTING" ]; then
  echo "No open failure issue for '$WORKFLOW'."
  exit 0
fi

# The reporter matches this prefix to reset its streak; the harness checks they
# agree.
RECOVERY_PREFIX="Recovered"

# Names no trigger: the flakiness report also resolves on `workflow_dispatch`.
gh issue comment "$EXISTING" --body "$RECOVERY_PREFIX — the workflow succeeded. Closing.

---
_Generated by [Claude Code](https://claude.ai/code)_"
gh issue close "$EXISTING" --reason completed
echo "Closed issue #$EXISTING"
