//! Token usage: [`UsageMetadata`] and its per-modality and per-tool
//! breakdowns. See the [parent module](super).

use serde::{Deserialize, Deserializer, Serialize};

// =============================================================================
// Token Count Deserialization Helpers
// =============================================================================

/// Deserializes a token count as `u32`, warning if the JSON value is negative.
///
/// Token counts should never be negative, but we handle this gracefully per
/// Evergreen principles. Negative values are clamped to 0 with a warning log.
fn deserialize_token_count<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: Deserializer<'de>,
{
    let value = i64::deserialize(deserializer)?;
    if value < 0 {
        tracing::warn!(
            "Received negative token count from API: {}. Clamping to 0.",
            value
        );
        Ok(0)
    } else if value > u32::MAX as i64 {
        tracing::warn!(
            "Token count exceeds u32::MAX: {}. Clamping to u32::MAX.",
            value
        );
        Ok(u32::MAX)
    } else {
        Ok(value as u32)
    }
}

/// Deserializes an optional token count as `Option<u32>`, warning if negative.
fn deserialize_optional_token_count<'de, D>(deserializer: D) -> Result<Option<u32>, D::Error>
where
    D: Deserializer<'de>,
{
    let value: Option<i64> = Option::deserialize(deserializer)?;
    match value {
        None => Ok(None),
        Some(v) if v < 0 => {
            tracing::warn!(
                "Received negative token count from API: {}. Clamping to 0.",
                v
            );
            Ok(Some(0))
        }
        Some(v) if v > u32::MAX as i64 => {
            tracing::warn!("Token count exceeds u32::MAX: {}. Clamping to u32::MAX.", v);
            Ok(Some(u32::MAX))
        }
        Some(v) => Ok(Some(v as u32)),
    }
}

/// Token count for a specific modality.
///
/// Used in per-modality breakdowns like [`UsageMetadata::input_tokens_by_modality`].
///
/// # Example
///
/// ```no_run
/// # use genai_rs::UsageMetadata;
/// # let usage: UsageMetadata = Default::default();
/// if let Some(breakdown) = &usage.input_tokens_by_modality {
///     for modality_tokens in breakdown {
///         println!("{}: {} tokens", modality_tokens.modality, modality_tokens.tokens);
///     }
/// }
/// ```
#[derive(Clone, Deserialize, Serialize, Debug, PartialEq)]
#[non_exhaustive]
pub struct ModalityTokens {
    /// The modality type (e.g., "text", "image", "audio").
    ///
    /// Uses string for forward compatibility with new modalities per Evergreen principles.
    pub modality: String,
    /// Token count for this modality.
    ///
    /// Uses `u32` since token counts are never negative. If the API returns a negative
    /// value (which would be a bug), it's clamped to 0 with a warning log.
    #[serde(deserialize_with = "deserialize_token_count")]
    pub tokens: u32,
}

impl ModalityTokens {
    /// Creates a modality token count.
    ///
    /// This type is `#[non_exhaustive]` and derives neither `Default` nor
    /// anything else that would let a downstream crate build one, so without
    /// this constructor `serde` would be the only route to a value.
    #[must_use]
    pub fn new(modality: impl Into<String>, tokens: u32) -> Self {
        Self {
            modality: modality.into(),
            tokens,
        }
    }
}

/// Per-tool grounding invocation count.
///
/// Reported in [`UsageMetadata::grounding_tool_count`]. Known `tool_type`
/// values are `google_search`, `google_maps`, and `retrieval`; the field is a
/// plain string for Evergreen forward compatibility.
#[derive(Clone, Deserialize, Serialize, Debug, Default, PartialEq, Eq)]
#[serde(default)]
#[non_exhaustive]
pub struct GroundingToolCount {
    /// The grounding tool type (wire field: `type`).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub tool_type: Option<String>,
    /// Number of invocations of this tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<u32>,
}

/// Token usage information from the Interactions API.
///
/// All token counts use `u32` since they're never negative. If the API returns
/// a negative value (which would be a bug), it's clamped to 0 with a warning log.
#[derive(Clone, Deserialize, Serialize, Debug, Default, PartialEq)]
#[serde(default)]
#[non_exhaustive]
pub struct UsageMetadata {
    /// Total number of input tokens (prompt tokens sent to the model)
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_optional_token_count"
    )]
    pub total_input_tokens: Option<u32>,
    /// Total number of output tokens (tokens generated by the model)
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_optional_token_count"
    )]
    pub total_output_tokens: Option<u32>,
    /// Total number of tokens (input + output)
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_optional_token_count"
    )]
    pub total_tokens: Option<u32>,
    /// Total number of cached tokens, which reduce billing.
    ///
    /// This is **implicit** caching, applied by the API with no
    /// configuration. Explicit context caching is not available on the
    /// Interactions API: the request field is rejected at every spelling and
    /// at both the top level and inside `generation_config` (verified live
    /// 2026-08-16), so there is nothing to pair this with — a non-zero value
    /// here is the whole story.
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_optional_token_count"
    )]
    pub total_cached_tokens: Option<u32>,
    /// Total number of thought tokens (thinking model internal reasoning)
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_optional_token_count"
    )]
    pub total_thought_tokens: Option<u32>,
    /// Total number of tokens used for tool/function calling overhead.
    ///
    /// Declaration alone is not counted: measured 2026-08-16, an interaction
    /// declaring an MCP server but answering from the model's own knowledge
    /// returns `Some(0)`, identical to the same prompt with no tool
    /// declared. So a non-zero value means a tool was actually invoked,
    /// which makes this the usable signal for server-side tools whose steps
    /// the API does not yet report by type (see `docs/BUILT_IN_TOOLS.md`).
    /// It is a single aggregate across all tools, though, so it identifies
    /// *which* tool only when one is declared —
    /// [`InteractionResponse::tool_use_tokens`] is the caller-facing
    /// accessor and carries the fuller story.
    ///
    /// [`InteractionResponse::tool_use_tokens`]: crate::InteractionResponse::tool_use_tokens
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_optional_token_count"
    )]
    pub total_tool_use_tokens: Option<u32>,

    // =========================================================================
    // Per-Modality Breakdowns
    // =========================================================================
    /// Input token counts broken down by modality (text, image, audio).
    ///
    /// Useful for understanding cost distribution in multi-modal prompts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens_by_modality: Option<Vec<ModalityTokens>>,

    /// Output token counts broken down by modality.
    ///
    /// Useful for understanding output cost distribution in multi-modal responses.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens_by_modality: Option<Vec<ModalityTokens>>,

    /// Cached token counts broken down by modality.
    ///
    /// Shows which modalities benefit from context caching.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens_by_modality: Option<Vec<ModalityTokens>>,

    /// Tool use token counts broken down by modality.
    ///
    /// Shows tool invocation overhead per modality.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_use_tokens_by_modality: Option<Vec<ModalityTokens>>,

    /// Per-tool grounding invocation counts (e.g., how many Google Search
    /// calls were made while grounding this interaction).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grounding_tool_count: Option<Vec<GroundingToolCount>>,

    /// Fields the API returned that this struct does not model, preserved
    /// for roundtrip (Evergreen). Live responses carry `raw_prompt_token`,
    /// `model_invocation_token_counts` and
    /// `non_grounding_model_invocation_token_counts`, none of which are in
    /// the bindings (2026-09-24).
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl UsageMetadata {
    /// Returns true if any usage data is present
    #[must_use]
    pub fn has_data(&self) -> bool {
        self.total_tokens.is_some()
            || self.total_input_tokens.is_some()
            || self.total_output_tokens.is_some()
            || self.total_cached_tokens.is_some()
            || self.total_thought_tokens.is_some()
            || self.total_tool_use_tokens.is_some()
            || self.input_tokens_by_modality.is_some()
            || self.output_tokens_by_modality.is_some()
            || self.cached_tokens_by_modality.is_some()
            || self.tool_use_tokens_by_modality.is_some()
            || self.grounding_tool_count.is_some()
    }

    /// Returns total thought tokens (thinking model internal reasoning)
    #[must_use]
    pub fn thought_tokens(&self) -> Option<u32> {
        self.total_thought_tokens
    }

    /// Returns the input token count for a specific modality.
    ///
    /// # Arguments
    ///
    /// * `modality` - The modality name (e.g., "text", "image", "audio")
    ///
    /// # Returns
    ///
    /// The token count for the specified modality, or `None` if the modality
    /// is not present in the breakdown or if modality data is unavailable.
    #[must_use]
    pub fn input_tokens_for_modality(&self, modality: &str) -> Option<u32> {
        self.input_tokens_by_modality
            .as_ref()?
            .iter()
            .find(|m| m.modality == modality)
            .map(|m| m.tokens)
    }

    /// Returns the grounding invocation count for a specific tool type.
    ///
    /// # Arguments
    ///
    /// * `tool_type` - The tool type (e.g., "google_search", "google_maps", "retrieval")
    #[must_use]
    pub fn grounding_count_for_tool(&self, tool_type: &str) -> Option<u32> {
        self.grounding_tool_count
            .as_ref()?
            .iter()
            .find(|g| g.tool_type.as_deref() == Some(tool_type))
            .and_then(|g| g.count)
    }

    /// Returns the cache hit rate as a fraction (0.0 to 1.0).
    ///
    /// The cache hit rate is the ratio of cached tokens to total input tokens.
    /// A higher rate indicates better cache utilization and lower costs.
    ///
    /// # Returns
    ///
    /// - `Some(rate)` where `rate` is between 0.0 and 1.0
    /// - `None` if either `total_cached_tokens` or `total_input_tokens` is unavailable,
    ///   or if `total_input_tokens` is zero
    #[must_use]
    pub fn cache_hit_rate(&self) -> Option<f32> {
        let cached = self.total_cached_tokens? as f32;
        let total = self.total_input_tokens? as f32;
        if total > 0.0 {
            Some(cached / total)
        } else {
            None
        }
    }

    /// Accumulates usage from another `UsageMetadata` into this one.
    ///
    /// This is useful for aggregating token counts across multiple API calls,
    /// such as in auto-function calling loops where each iteration reports
    /// its own usage.
    ///
    /// For each field, if the other has a value:
    /// - If self has a value, adds the other's value
    /// - If self has None, takes the other's value
    ///
    /// Note: `*_by_modality` and `grounding_tool_count` fields are not
    /// accumulated (would require complex merging).
    pub(crate) fn accumulate(&mut self, other: &UsageMetadata) {
        fn add_option(a: &mut Option<u32>, b: Option<u32>) {
            if let Some(b_val) = b {
                *a = Some(a.unwrap_or(0).saturating_add(b_val));
            }
        }

        add_option(&mut self.total_input_tokens, other.total_input_tokens);
        add_option(&mut self.total_output_tokens, other.total_output_tokens);
        add_option(&mut self.total_tokens, other.total_tokens);
        add_option(&mut self.total_cached_tokens, other.total_cached_tokens);
        add_option(&mut self.total_thought_tokens, other.total_thought_tokens);
        add_option(&mut self.total_tool_use_tokens, other.total_tool_use_tokens);
        // Note: *_by_modality and grounding_tool_count fields are not
        // accumulated as they would require complex merging logic.
    }
}

#[cfg(test)]
#[path = "usage_tests.rs"]
mod tests;
